apiVersion: v1
kind: Service
metadata:
  name: django-metrics
  namespace: default
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
