image:
  repository: 020236748758.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-18062025214500
  tag: v1.0.30
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
  SECRET_KEY: "django-insecure-u(qc9*j0w=ut5db3f#izfz_8szd7rruds!p8p5hgwz0in=+s7t"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,.us-east-1.elb.amazonaws.com"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
