image:
  repository: 020236748758.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-18062025214500
  tag: v1.0.6
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000
  metricsPort: 8001

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
